<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>BentPlateGeometrySolver.AddLeg Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="AddLeg method" /><meta name="System.Keywords" content="BentPlateGeometrySolver.AddLeg method" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.BentPlateGeometrySolver.AddLeg" /><meta name="Microsoft.Help.Id" content="Overload:Tekla.Structures.Model.BentPlateGeometrySolver.AddLeg" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model" /><meta name="file" content="0d2804d7-a09f-a4f0-0d98-d2a0da906df4" /><meta name="guid" content="0d2804d7-a09f-a4f0-0d98-d2a0da906df4" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>BentPlateGeometrySolver<span id="LST543AE84A_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST543AE84A_0?cpp=::|nu=.");</script>AddLeg Method </h1></td></tr></table><span class="introStyle"></span> <div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Overload List</span></div><div id="ID0RBSection" class="collapsibleSection"><table class="members" id="overloadMembersList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="a2759dfe-8879-387a-43c8-a30e76609c81.htm">AddLeg(ConnectiveGeometry, Contour)</a></td><td><div class="summary">
            Appends a polygon section to ConnectiveGeometry, using the maximal radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="be684308-bd46-4b43-ab67-885df4db987f.htm">AddLeg(ConnectiveGeometry, Contour, Double)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="01139736-16e5-b503-b77c-2a989302924e.htm">AddLeg(ConnectiveGeometry, Contour, BentPlate<span id="LST543AE84A_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST543AE84A_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape)</a></td><td><div class="summary">
            Appends a polygon section to ConnectiveGeometry, using the maximal radius for the cylindrical connection, or
            the maximum cone aperture for conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="fe3ef7c1-95d0-b903-029f-3327db769d09.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified connection points and maximal radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="005a09fb-64f4-0150-fdee-40ba1d2e009e.htm">AddLeg(ConnectiveGeometry, Contour, Double, Double)</a></td><td><div class="summary">
            Joins a polygon section to this ConnectiveGeometry, using the specified radius and aperture for the conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="3381e0db-8efa-f82b-8322-f4a48ed1a265.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment, Double)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified connection points and radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="2ae3af3f-6bf8-1f24-e666-c55aca86f5c4.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment, BentPlate<span id="LST543AE84A_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST543AE84A_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified connection points and maximal
            radius for the cylindrical connection, or maximum aperture for conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="253cf055-768d-0624-e258-2039cd78494d.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment, Double, Double)</a></td><td><div class="summary">
            Joins a polygon section to this ConnectiveGeometry, using the specified connection points and radius
            and aperture for the conical connection.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID1RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="6868795d-e6b6-4c94-a705-5e4972e535c9.htm">BentPlateGeometrySolver Class</a></div><div class="seeAlsoStyle"><a href="ead2dd1b-97f2-a283-bd41-e985db80929d.htm">Tekla.Structures.Model Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>