<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Operation.CreateBentPlateByFaces Method (Part, IList(Point), Part, IList(Point), BentPlate.BendShape)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Tekla.Structures.Model.Operations.Operation.CreateBentPlateByFaces(Tekla.Structures.Model.Part,System.Collections.Generic.IList{Tekla.Structures.Geometry3d.Point},Tekla.Structures.Model.Part,System.Collections.Generic.IList{Tekla.Structures.Geometry3d.Point},Tekla.Structures.Model.BentPlate.BendShape)" /><meta name="Description" content="Modifies the first plate by adding a bend that connects it to the second plate creating a new instance based on two parts and selected faces in each part. This method can change GUID when using from plug-ins. To keep GUID, use ." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model.Operations" /><meta name="file" content="0dca7df4-8430-6f6c-e648-2d40134a06a7" /><meta name="guid" content="0dca7df4-8430-6f6c-e648-2d40134a06a7" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>Operation<span id="LSTDF0FFB1F_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_0?cpp=::|nu=.");</script>CreateBentPlateByFaces Method (Part, IList<span id="LSTDF0FFB1F_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_1?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Point<span id="LSTDF0FFB1F_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_2?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>, Part, IList<span id="LSTDF0FFB1F_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_3?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Point<span id="LSTDF0FFB1F_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_4?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>, BentPlate<span id="LSTDF0FFB1F_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_5?cpp=::|nu=.");</script>BendShape)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Modifies the first plate by adding a bend that connects it to the second plate
            creating a new <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a> instance based on two parts and selected faces in each part.
            This method can change GUID when using from plug-ins.
            To keep GUID, use <span class="nolink">AddLeg(ConnectiveGeometry, LineSegment, ConnectiveGeometry, LineSegment, BentPlate<span id="LSTDF0FFB1F_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_6?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape)</span>.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Model (in Tekla.Structures.Model.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">BentPlate</span> <span class="identifier">CreateBentPlateByFaces</span>(
	<span class="identifier">Part</span> <span class="parameter">part1</span>,
	<span class="identifier">IList</span>&lt;<span class="identifier">Point</span>&gt; <span class="parameter">face1</span>,
	<span class="identifier">Part</span> <span class="parameter">part2</span>,
	<span class="identifier">IList</span>&lt;<span class="identifier">Point</span>&gt; <span class="parameter">face2</span>,
	<span class="identifier">BentPlate<span id="LSTDF0FFB1F_7"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_7?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape</span> <span class="parameter">bendShape</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CreateBentPlateByFaces</span> ( 
	<span class="parameter">part1</span> <span class="keyword">As</span> <span class="identifier">Part</span>,
	<span class="parameter">face1</span> <span class="keyword">As</span> <span class="identifier">IList</span>(<span class="keyword">Of</span> <span class="identifier">Point</span>),
	<span class="parameter">part2</span> <span class="keyword">As</span> <span class="identifier">Part</span>,
	<span class="parameter">face2</span> <span class="keyword">As</span> <span class="identifier">IList</span>(<span class="keyword">Of</span> <span class="identifier">Point</span>),
	<span class="parameter">bendShape</span> <span class="keyword">As</span> <span class="identifier">BentPlate<span id="LSTDF0FFB1F_8"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_8?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape</span>
) <span class="keyword">As</span> <span class="identifier">BentPlate</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">part1</span></dt><dd>Type: <a href="ac720ea3-a9ae-235b-d627-c9c37585b6ec.htm">Tekla.Structures.Model<span id="LSTDF0FFB1F_9"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_9?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Part</a><br />The first part.</dd><dt><span class="parameter">face1</span></dt><dd>Type: <span class="nolink">System.Collections.Generic<span id="LSTDF0FFB1F_10"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_10?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IList</span><span id="LSTDF0FFB1F_11"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_11?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Point</a><span id="LSTDF0FFB1F_12"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_12?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />The selected face on the first part.</dd><dt><span class="parameter">part2</span></dt><dd>Type: <a href="ac720ea3-a9ae-235b-d627-c9c37585b6ec.htm">Tekla.Structures.Model<span id="LSTDF0FFB1F_13"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_13?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Part</a><br />The second part.</dd><dt><span class="parameter">face2</span></dt><dd>Type: <span class="nolink">System.Collections.Generic<span id="LSTDF0FFB1F_14"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_14?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IList</span><span id="LSTDF0FFB1F_15"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_15?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Point</a><span id="LSTDF0FFB1F_16"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_16?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />The selected face on the second part.</dd><dt><span class="parameter">bendShape</span></dt><dd>Type: <a href="b5343f3c-931a-194b-ccc5-e1c29895b276.htm">Tekla.Structures.Model<span id="LSTDF0FFB1F_17"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_17?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BentPlate<span id="LSTDF0FFB1F_18"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTDF0FFB1F_18?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape</a><br />Shape of the bend (cylindrical or conical)</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a><br />The bent plate object if successful, null otherwise.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Exceptions</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="tableSection"><table><tr><th>Exception</th><th>Condition</th></tr><tr><td><a href="bb701f1a-d0bc-4b22-23ab-8484219793af.htm">ConnectiveGeometryException</a></td><td>Thrown if could not create ConnectiveGeometry instance.</td></tr><tr><td><span class="nolink">ArgumentException</span></td><td>Thrown when faces have incorrect number of face points or received unsupported bent plate creation input.</td></tr></table></div></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="d5bbc096-a164-49ea-16a8-3820e40b00be.htm">Operation Class</a></div><div class="seeAlsoStyle"><a href="fe47d253-6b7e-3119-0f20-5ba244c9fd65.htm">CreateBentPlateByFaces Overload</a></div><div class="seeAlsoStyle"><a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>