<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Operation.CreateConicalBentPlateByFaces Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="CreateConicalBentPlateByFaces method" /><meta name="System.Keywords" content="Operation.CreateConicalBentPlateByFaces method" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.Operations.Operation.CreateConicalBentPlateByFaces" /><meta name="Microsoft.Help.Id" content="Overload:Tekla.Structures.Model.Operations.Operation.CreateConicalBentPlateByFaces" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model.Operations" /><meta name="file" content="382ee4e5-f707-2948-1e6e-9396835fd630" /><meta name="guid" content="382ee4e5-f707-2948-1e6e-9396835fd630" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>Operation<span id="LSTE40119B2_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTE40119B2_0?cpp=::|nu=.");</script>CreateConicalBentPlateByFaces Method </h1></td></tr></table><span class="introStyle"></span> <div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Overload List</span></div><div id="ID0RBSection" class="collapsibleSection"><table class="members" id="overloadMembersList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="b70630f0-c290-2237-1249-f37b1e6d4469.htm">CreateConicalBentPlateByFaces(Part, IList<span id="LSTE40119B2_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTE40119B2_1?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Point<span id="LSTE40119B2_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTE40119B2_2?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>, Part, IList<span id="LSTE40119B2_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTE40119B2_3?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Point<span id="LSTE40119B2_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTE40119B2_4?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>, Double, Double)</a></td><td><div class="summary">
            Modifies the first plate by adding a conical bend that connects it to the second plate
            creating a new <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a> instance based on two parts, selected faces in each part and radius.
            This method can change GUID when using from plug-ins.
            To keep GUID, use <span class="nolink">AddLeg(ConnectiveGeometry, LineSegment, ConnectiveGeometry, LineSegment, Double)</span>.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="3e17cb16-5db2-96ff-a9bc-7b6ac320e2b9.htm">CreateConicalBentPlateByFaces(Part, Face, Part, Face, Double, Double)</a></td><td><div class="summary">
            Modifies the first plate by adding a conical bend that connects it to the second plate
            creating a new <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a> instance based on two parts and selected faces in each part, and the
            largest radius of the conical section and the cone aperture.
            This method can change GUID when using from plug-ins.
            To keep GUID, use <span class="nolink">AddLeg(ConnectiveGeometry, LineSegment, ConnectiveGeometry, LineSegment, Double)</span>.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID1RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="d5bbc096-a164-49ea-16a8-3820e40b00be.htm">Operation Class</a></div><div class="seeAlsoStyle"><a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>