<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ModelObject.ModelObjectEnum Enumeration</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="ModelObject.ModelObjectEnum enumeration" /><meta name="System.Keywords" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum enumeration" /><meta name="System.Keywords" content="UNKNOWN enumeration member" /><meta name="System.Keywords" content="BEAM enumeration member" /><meta name="System.Keywords" content="POLYBEAM enumeration member" /><meta name="System.Keywords" content="CONTOURPLATE enumeration member" /><meta name="System.Keywords" content="BOOLEANPART enumeration member" /><meta name="System.Keywords" content="FITTING enumeration member" /><meta name="System.Keywords" content="CUTPLANE enumeration member" /><meta name="System.Keywords" content="SURFACE_TREATMENT enumeration member" /><meta name="System.Keywords" content="WELD enumeration member" /><meta name="System.Keywords" content="ASSEMBLY enumeration member" /><meta name="System.Keywords" content="SINGLEREBAR enumeration member" /><meta name="System.Keywords" content="REBARGROUP enumeration member" /><meta name="System.Keywords" content="REBARMESH enumeration member" /><meta name="System.Keywords" content="REBARSTRAND enumeration member" /><meta name="System.Keywords" content="CONTROL_PLANE enumeration member" /><meta name="System.Keywords" content="BOLT_ARRAY enumeration member" /><meta name="System.Keywords" content="BOLT_CIRCLE enumeration member" /><meta name="System.Keywords" content="BOLT_XYLIST enumeration member" /><meta name="System.Keywords" content="LOAD_POINT enumeration member" /><meta name="System.Keywords" content="LOAD_LINE enumeration member" /><meta name="System.Keywords" content="LOAD_AREA enumeration member" /><meta name="System.Keywords" content="LOAD_UNIFORM enumeration member" /><meta name="System.Keywords" content="GRID enumeration member" /><meta name="System.Keywords" content="GRIDPLANE enumeration member" /><meta name="System.Keywords" content="CONNECTION enumeration member" /><meta name="System.Keywords" content="COMPONENT enumeration member" /><meta name="System.Keywords" content="SEAM enumeration member" /><meta name="System.Keywords" content="DETAIL enumeration member" /><meta name="System.Keywords" content="REFERENCE_MODEL enumeration member" /><meta name="System.Keywords" content="REBAR_SPLICE enumeration member" /><meta name="System.Keywords" content="LOAD_GROUP enumeration member" /><meta name="System.Keywords" content="TASK enumeration member" /><meta name="System.Keywords" content="TASK_DEPENDENCY enumeration member" /><meta name="System.Keywords" content="TASK_WORKTYPE enumeration member" /><meta name="System.Keywords" content="POLYGON_WELD enumeration member" /><meta name="System.Keywords" content="LOGICAL_WELD enumeration member" /><meta name="System.Keywords" content="CIRCLEREBAR enumeration member" /><meta name="System.Keywords" content="HIERARCHIC_DEFINITION enumeration member" /><meta name="System.Keywords" content="HIERARCHIC_OBJECT enumeration member" /><meta name="System.Keywords" content="ANALYSIS_GEOMETRY enumeration member" /><meta name="System.Keywords" content="ANALYSIS_PART enumeration member" /><meta name="System.Keywords" content="REFERENCE_MODEL_OBJECT enumeration member" /><meta name="System.Keywords" content="CUSTOM_PART enumeration member" /><meta name="System.Keywords" content="CIRCLE_REBARGROUP enumeration member" /><meta name="System.Keywords" content="CURVED_REBARGROUP enumeration member" /><meta name="System.Keywords" content="EDGE_CHAMFER enumeration member" /><meta name="System.Keywords" content="POUR_OBJECT enumeration member" /><meta name="System.Keywords" content="POUR_BREAK enumeration member" /><meta name="System.Keywords" content="CONTROL_LINE enumeration member" /><meta name="System.Keywords" content="LOAD_TEMPERATURE enumeration member" /><meta name="System.Keywords" content="BREP enumeration member" /><meta name="System.Keywords" content="CONTROL_CIRCLE enumeration member" /><meta name="System.Keywords" content="CONTROL_POINT enumeration member" /><meta name="System.Keywords" content="REBAR_SET enumeration member" /><meta name="System.Keywords" content="REBAR_SET_ADDITION enumeration member" /><meta name="System.Keywords" content="REBAR_PROPERTY_MODIFIER enumeration member" /><meta name="System.Keywords" content="REBAR_END_DETAIL_MODIFIER enumeration member" /><meta name="System.Keywords" content="REBAR_SPLITTER enumeration member" /><meta name="System.Keywords" content="CONTROL_ARC enumeration member" /><meta name="System.Keywords" content="CONTROL_SPLINE enumeration member" /><meta name="System.Keywords" content="CONTROL_POLYCURVE enumeration member" /><meta name="System.Keywords" content="RADIAL_GRID enumeration member" /><meta name="System.Keywords" content="GRID_CYLINDRICAL_SURFACE enumeration member" /><meta name="System.Keywords" content="LOFTED_PLATE enumeration member" /><meta name="System.Keywords" content="LEG_SURFACE_OBJECT enumeration member" /><meta name="System.Keywords" content="STOREY enumeration member" /><meta name="System.Keywords" content="SPACE enumeration member" /><meta name="System.Keywords" content="BUILDING enumeration member" /><meta name="System.Keywords" content="BUILDING_SITE enumeration member" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.UNKNOWN" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BEAM" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.POLYBEAM" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTOURPLATE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOOLEANPART" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.FITTING" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CUTPLANE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.SURFACE_TREATMENT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.WELD" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.ASSEMBLY" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.SINGLEREBAR" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBARGROUP" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBARMESH" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBARSTRAND" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_PLANE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOLT_ARRAY" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOLT_CIRCLE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOLT_XYLIST" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_POINT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_LINE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_AREA" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_UNIFORM" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.GRID" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.GRIDPLANE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONNECTION" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.COMPONENT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.SEAM" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.DETAIL" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REFERENCE_MODEL" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SPLICE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_GROUP" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.TASK" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.TASK_DEPENDENCY" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.TASK_WORKTYPE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.POLYGON_WELD" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOGICAL_WELD" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CIRCLEREBAR" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.HIERARCHIC_DEFINITION" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.HIERARCHIC_OBJECT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.ANALYSIS_GEOMETRY" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.ANALYSIS_PART" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REFERENCE_MODEL_OBJECT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CUSTOM_PART" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CIRCLE_REBARGROUP" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CURVED_REBARGROUP" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.EDGE_CHAMFER" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.POUR_OBJECT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.POUR_BREAK" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_LINE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_TEMPERATURE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BREP" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_CIRCLE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_POINT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SET" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SET_ADDITION" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_PROPERTY_MODIFIER" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_END_DETAIL_MODIFIER" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SPLITTER" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_ARC" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_SPLINE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_POLYCURVE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.RADIAL_GRID" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.GRID_CYLINDRICAL_SURFACE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOFTED_PLATE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.LEG_SURFACE_OBJECT" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.STOREY" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.SPACE" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BUILDING" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.ModelObject.ModelObjectEnum.BUILDING_SITE" /><meta name="Microsoft.Help.Id" content="T:Tekla.Structures.Model.ModelObject.ModelObjectEnum" /><meta name="Description" content="All possible concrete model object subclasses are defined here. This enumeration can be used to fetch certain types of objects from the Tekla Structures model." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model" /><meta name="file" content="40af6269-5d48-d7a0-3b34-95ef2f744c3e" /><meta name="guid" content="40af6269-5d48-d7a0-3b34-95ef2f744c3e" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>ModelObject<span id="LST7CAB65C6_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST7CAB65C6_0?cpp=::|nu=.");</script>ModelObjectEnum Enumeration</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            All possible concrete model object subclasses are defined here. This enumeration can be used to
            fetch certain types of objects from the Tekla Structures model.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="ead2dd1b-97f2-a283-bd41-e985db80929d.htm">Tekla.Structures.Model</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Model (in Tekla.Structures.Model.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">enum</span> <span class="identifier">ModelObjectEnum</span></pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Enumeration</span> <span class="identifier">ModelObjectEnum</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script></div><div id="enumerationSection"><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Members</span></div><div id="ID2RBSection" class="collapsibleSection"><table id="enumMemberList" class="members"><tr><th class="iconColumn">
									 
								</th><th>Member name</th><th>Value</th><th>Description</th></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.UNKNOWN"><span class="selflink">UNKNOWN</span></td><td>0</td><td>
            The unknown model object.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BEAM"><span class="selflink">BEAM</span></td><td>1</td><td>
            The beam.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.POLYBEAM"><span class="selflink">POLYBEAM</span></td><td>2</td><td>
            The polybeam.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTOURPLATE"><span class="selflink">CONTOURPLATE</span></td><td>3</td><td>
            The contour plate.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOOLEANPART"><span class="selflink">BOOLEANPART</span></td><td>4</td><td>
            The boolean part.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.FITTING"><span class="selflink">FITTING</span></td><td>5</td><td>
            The fitting.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CUTPLANE"><span class="selflink">CUTPLANE</span></td><td>6</td><td>
            The cutplane.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.SURFACE_TREATMENT"><span class="selflink">SURFACE_TREATMENT</span></td><td>7</td><td>
            The surface treatment.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.WELD"><span class="selflink">WELD</span></td><td>8</td><td>
            The weld.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.ASSEMBLY"><span class="selflink">ASSEMBLY</span></td><td>9</td><td>
            The assembly.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.SINGLEREBAR"><span class="selflink">SINGLEREBAR</span></td><td>10</td><td>
            The single rebar.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBARGROUP"><span class="selflink">REBARGROUP</span></td><td>11</td><td>
            The rebar group.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBARMESH"><span class="selflink">REBARMESH</span></td><td>12</td><td>
            The rebar mesh.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBARSTRAND"><span class="selflink">REBARSTRAND</span></td><td>13</td><td>
            The rebar strand.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_PLANE"><span class="selflink">CONTROL_PLANE</span></td><td>14</td><td>
            The control plane.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOLT_ARRAY"><span class="selflink">BOLT_ARRAY</span></td><td>15</td><td>
            The bolt array.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOLT_CIRCLE"><span class="selflink">BOLT_CIRCLE</span></td><td>16</td><td>
            The bolt circle.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BOLT_XYLIST"><span class="selflink">BOLT_XYLIST</span></td><td>17</td><td>
            The bolt XY list.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_POINT"><span class="selflink">LOAD_POINT</span></td><td>18</td><td>
            The point load.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_LINE"><span class="selflink">LOAD_LINE</span></td><td>19</td><td>
            The line load.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_AREA"><span class="selflink">LOAD_AREA</span></td><td>20</td><td>
            The area load.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_UNIFORM"><span class="selflink">LOAD_UNIFORM</span></td><td>21</td><td>
            The uniform load.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.GRID"><span class="selflink">GRID</span></td><td>22</td><td>
            The grid.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.GRIDPLANE"><span class="selflink">GRIDPLANE</span></td><td>23</td><td>
            The grid plane.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONNECTION"><span class="selflink">CONNECTION</span></td><td>24</td><td>
            The connection.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.COMPONENT"><span class="selflink">COMPONENT</span></td><td>25</td><td>
            The component.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.SEAM"><span class="selflink">SEAM</span></td><td>26</td><td>
            The seam.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.DETAIL"><span class="selflink">DETAIL</span></td><td>27</td><td>
            The detail.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REFERENCE_MODEL"><span class="selflink">REFERENCE_MODEL</span></td><td>28</td><td>
            The reference model.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SPLICE"><span class="selflink">REBAR_SPLICE</span></td><td>29</td><td>
            The rebar splice.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_GROUP"><span class="selflink">LOAD_GROUP</span></td><td>30</td><td>
            The load group.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.TASK"><span class="selflink">TASK</span></td><td>31</td><td>
            The task.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.TASK_DEPENDENCY"><span class="selflink">TASK_DEPENDENCY</span></td><td>32</td><td>
            The task dependency.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.TASK_WORKTYPE"><span class="selflink">TASK_WORKTYPE</span></td><td>34</td><td>
            The task worktype.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.POLYGON_WELD"><span class="selflink">POLYGON_WELD</span></td><td>35</td><td>
            The polygon weld.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOGICAL_WELD"><span class="selflink">LOGICAL_WELD</span></td><td>36</td><td>
            The logical weld.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CIRCLEREBAR"><span class="selflink">CIRCLEREBAR</span></td><td>37</td><td>
            The circle rebar.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.HIERARCHIC_DEFINITION"><span class="selflink">HIERARCHIC_DEFINITION</span></td><td>38</td><td>
            The hierarchic definition.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.HIERARCHIC_OBJECT"><span class="selflink">HIERARCHIC_OBJECT</span></td><td>39</td><td>
            The hierarchic object.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.ANALYSIS_GEOMETRY"><span class="selflink">ANALYSIS_GEOMETRY</span></td><td>40</td><td>
            The analysis geometry.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.ANALYSIS_PART"><span class="selflink">ANALYSIS_PART</span></td><td>41</td><td>
            The analysis part.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REFERENCE_MODEL_OBJECT"><span class="selflink">REFERENCE_MODEL_OBJECT</span></td><td>42</td><td>
            The reference model object.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CUSTOM_PART"><span class="selflink">CUSTOM_PART</span></td><td>43</td><td>
            The custom part object.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CIRCLE_REBARGROUP"><span class="selflink">CIRCLE_REBARGROUP</span></td><td>44</td><td>
            The circle rebar group.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CURVED_REBARGROUP"><span class="selflink">CURVED_REBARGROUP</span></td><td>45</td><td>
            The curved rebar group.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.EDGE_CHAMFER"><span class="selflink">EDGE_CHAMFER</span></td><td>46</td><td>
            The edge chamfer.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.POUR_OBJECT"><span class="selflink">POUR_OBJECT</span></td><td>47</td><td>
            The pour object.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.POUR_BREAK"><span class="selflink">POUR_BREAK</span></td><td>48</td><td>
            The pour break.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_LINE"><span class="selflink">CONTROL_LINE</span></td><td>50</td><td>
            The control line.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOAD_TEMPERATURE"><span class="selflink">LOAD_TEMPERATURE</span></td><td>51</td><td>
            The temperature load.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BREP"><span class="selflink">BREP</span></td><td>52</td><td>
            The Brep part instance.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_CIRCLE"><span class="selflink">CONTROL_CIRCLE</span></td><td>53</td><td>
            The control circle.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_POINT"><span class="selflink">CONTROL_POINT</span></td><td>54</td><td>
            The control point.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SET"><span class="selflink">REBAR_SET</span></td><td>55</td><td>
            The rebar set.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SET_ADDITION"><span class="selflink">REBAR_SET_ADDITION</span></td><td>56</td><td>
            The rebar set addition.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_PROPERTY_MODIFIER"><span class="selflink">REBAR_PROPERTY_MODIFIER</span></td><td>57</td><td>
            The rebar property modifier.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_END_DETAIL_MODIFIER"><span class="selflink">REBAR_END_DETAIL_MODIFIER</span></td><td>58</td><td>
            The rebar end-detail modifier.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.REBAR_SPLITTER"><span class="selflink">REBAR_SPLITTER</span></td><td>59</td><td>
            The rebar splitter.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_ARC"><span class="selflink">CONTROL_ARC</span></td><td>64</td><td>
            Construction arc.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_SPLINE"><span class="selflink">CONTROL_SPLINE</span></td><td>65</td><td>
            Construction spline
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.CONTROL_POLYCURVE"><span class="selflink">CONTROL_POLYCURVE</span></td><td>66</td><td>
            Construction polycurve
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.RADIAL_GRID"><span class="selflink">RADIAL_GRID</span></td><td>67</td><td>
            Radial grid
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.GRID_CYLINDRICAL_SURFACE"><span class="selflink">GRID_CYLINDRICAL_SURFACE</span></td><td>68</td><td>
            Cylindrical surfaces of radial grids
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LOFTED_PLATE"><span class="selflink">LOFTED_PLATE</span></td><td>69</td><td>
            The lofted plate
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.LEG_SURFACE_OBJECT"><span class="selflink">LEG_SURFACE_OBJECT</span></td><td>70</td><td>
            The leg surface object.
            </td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.STOREY"><span class="selflink">STOREY</span></td><td>71</td><td>The storey object.</td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.SPACE"><span class="selflink">SPACE</span></td><td>72</td><td>The building space object.</td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BUILDING"><span class="selflink">BUILDING</span></td><td>73</td><td>The building space object.</td></tr><tr><td /><td target="F:Tekla.Structures.Model.ModelObject.ModelObjectEnum.BUILDING_SITE"><span class="selflink">BUILDING_SITE</span></td><td>74</td><td>The site object.</td></tr></table></div></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="ead2dd1b-97f2-a283-bd41-e985db80929d.htm">Tekla.Structures.Model Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>