<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Operation.CreateBentPlateByParts Method (Part, Part, Double)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Tekla.Structures.Model.Operations.Operation.CreateBentPlateByParts(Tekla.Structures.Model.Part,Tekla.Structures.Model.Part,System.Double)" /><meta name="Description" content="Modifies the first plate by adding a bend that connects it to the second plate creating a new instance based on two parts and a radius. This method can change GUID when using from plug-ins. To keep GUID, use ." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model.Operations" /><meta name="file" content="49a6d6e3-83ec-e179-c4c0-7545a44723d6" /><meta name="guid" content="49a6d6e3-83ec-e179-c4c0-7545a44723d6" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>Operation<span id="LST663EB749_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST663EB749_0?cpp=::|nu=.");</script>CreateBentPlateByParts Method (Part, Part, Double)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Modifies the first plate by adding a bend that connects it to the second plate
            creating a new <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a> instance based on two parts and a radius.
            This method can change GUID when using from plug-ins.
            To keep GUID, use <span class="nolink">AddLeg(ConnectiveGeometry, ConnectiveGeometry, Double)</span>.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Model (in Tekla.Structures.Model.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">BentPlate</span> <span class="identifier">CreateBentPlateByParts</span>(
	<span class="identifier">Part</span> <span class="parameter">part1</span>,
	<span class="identifier">Part</span> <span class="parameter">part2</span>,
	<span class="identifier">double</span> <span class="parameter">radius</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CreateBentPlateByParts</span> ( 
	<span class="parameter">part1</span> <span class="keyword">As</span> <span class="identifier">Part</span>,
	<span class="parameter">part2</span> <span class="keyword">As</span> <span class="identifier">Part</span>,
	<span class="parameter">radius</span> <span class="keyword">As</span> <span class="identifier">Double</span>
) <span class="keyword">As</span> <span class="identifier">BentPlate</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">part1</span></dt><dd>Type: <a href="ac720ea3-a9ae-235b-d627-c9c37585b6ec.htm">Tekla.Structures.Model<span id="LST663EB749_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST663EB749_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Part</a><br />One part used for creating the bent plate.</dd><dt><span class="parameter">part2</span></dt><dd>Type: <a href="ac720ea3-a9ae-235b-d627-c9c37585b6ec.htm">Tekla.Structures.Model<span id="LST663EB749_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST663EB749_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Part</a><br />The other part used for creating the bent plate.</dd><dt><span class="parameter">radius</span></dt><dd>Type: <span class="nolink">System<span id="LST663EB749_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST663EB749_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</span><br />The target radius for the created cylindrical section.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a><br />The bent plate object if successful, null otherwise</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Exceptions</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="tableSection"><table><tr><th>Exception</th><th>Condition</th></tr><tr><td><a href="bb701f1a-d0bc-4b22-23ab-8484219793af.htm">ConnectiveGeometryException</a></td><td>Thrown if could not create ConnectiveGeometry instance.</td></tr><tr><td><span class="nolink">ArgumentException</span></td><td>Thrown if received unsupported bent plate creation input.</td></tr></table></div></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="d5bbc096-a164-49ea-16a8-3820e40b00be.htm">Operation Class</a></div><div class="seeAlsoStyle"><a href="3d8a00d4-7b78-071c-22d7-71f3fff8a4ad.htm">CreateBentPlateByParts Overload</a></div><div class="seeAlsoStyle"><a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>