<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>CurvedDimensionRadial Constructor (ViewBase, Point, Point, Point, Point, Point, Double, CurvedDimensionSetRadial.CurvedDimensionSetRadialAttributes)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Tekla.Structures.Drawing.CurvedDimensionRadial.#ctor(Tekla.Structures.Drawing.ViewBase,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Geometry3d.Point,System.Double,Tekla.Structures.Drawing.CurvedDimensionSetRadial.CurvedDimensionSetRadialAttributes)" /><meta name="Description" content="Creates a new curved dimension with radial reference points." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Drawing" /><meta name="file" content="63f1d671-8bef-fcda-7661-210af5f5408f" /><meta name="guid" content="63f1d671-8bef-fcda-7661-210af5f5408f" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>CurvedDimensionRadial Constructor (ViewBase, Point, Point, Point, Point, Point, Double, CurvedDimensionSetRadial<span id="LST5750700_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_0?cpp=::|nu=.");</script>CurvedDimensionSetRadialAttributes)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Creates a new curved dimension with radial reference points.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="77c95495-6298-e2ff-cdf9-2ad5ff176015.htm">Tekla.Structures.Drawing</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Drawing (in Tekla.Structures.Drawing.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">CurvedDimensionRadial</span>(
	<span class="identifier">ViewBase</span> <span class="parameter">View</span>,
	<span class="identifier">Point</span> <span class="parameter">ArcPoint1</span>,
	<span class="identifier">Point</span> <span class="parameter">ArcPoint2</span>,
	<span class="identifier">Point</span> <span class="parameter">ArcPoint3</span>,
	<span class="identifier">Point</span> <span class="parameter">StartPoint</span>,
	<span class="identifier">Point</span> <span class="parameter">EndPoint</span>,
	<span class="identifier">double</span> <span class="parameter">Distance</span>,
	<span class="identifier">CurvedDimensionSetRadial<span id="LST5750700_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetRadialAttributes</span> <span class="parameter">Attributes</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Sub</span> <span class="identifier">New</span> ( 
	<span class="parameter">View</span> <span class="keyword">As</span> <span class="identifier">ViewBase</span>,
	<span class="parameter">ArcPoint1</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">ArcPoint2</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">ArcPoint3</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">StartPoint</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">EndPoint</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">Distance</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">Attributes</span> <span class="keyword">As</span> <span class="identifier">CurvedDimensionSetRadial<span id="LST5750700_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetRadialAttributes</span>
)</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">View</span></dt><dd>Type: <a href="474d3089-26da-d62c-0797-bcae0f714220.htm">Tekla.Structures.Drawing<span id="LST5750700_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>ViewBase</a><br />The view to be used.</dd><dt><span class="parameter">ArcPoint1</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LST5750700_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The first arc point to be used.</dd><dt><span class="parameter">ArcPoint2</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LST5750700_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_5?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The second arc point to be used.</dd><dt><span class="parameter">ArcPoint3</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LST5750700_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_6?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The third arc point to be used.</dd><dt><span class="parameter">StartPoint</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LST5750700_7"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_7?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The start point to be used.</dd><dt><span class="parameter">EndPoint</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LST5750700_8"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_8?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The end point to be used.</dd><dt><span class="parameter">Distance</span></dt><dd>Type: <span class="nolink">System<span id="LST5750700_9"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_9?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</span><br />The distance in paper millimeters.</dd><dt><span class="parameter">Attributes</span></dt><dd>Type: <a href="93e176d8-7aa3-89da-3e36-7968e250ef86.htm">Tekla.Structures.Drawing<span id="LST5750700_10"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_10?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetRadial<span id="LST5750700_11"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5750700_11?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetRadialAttributes</a><br />The attributes to be applied.</dd></dl></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="061b94cd-8971-4993-a437-736478c0a124.htm">CurvedDimensionRadial Class</a></div><div class="seeAlsoStyle"><a href="a9676e8f-4df2-3c14-eead-c8cd98e87710.htm">CurvedDimensionRadial Overload</a></div><div class="seeAlsoStyle"><a href="77c95495-6298-e2ff-cdf9-2ad5ff176015.htm">Tekla.Structures.Drawing Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>