<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>BentPlateGeometrySolver Class</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BentPlateGeometrySolver class" /><meta name="System.Keywords" content="Tekla.Structures.Model.BentPlateGeometrySolver class" /><meta name="System.Keywords" content="BentPlateGeometrySolver class, about BentPlateGeometrySolver class" /><meta name="Microsoft.Help.F1" content="Tekla.Structures.Model.BentPlateGeometrySolver" /><meta name="Microsoft.Help.Id" content="T:Tekla.Structures.Model.BentPlateGeometrySolver" /><meta name="Description" content="BentPlateGeometrySolver is a solver class to handle ConnectiveGeometry modification related computations." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model" /><meta name="file" content="6868795d-e6b6-4c94-a705-5e4972e535c9" /><meta name="guid" content="6868795d-e6b6-4c94-a705-5e4972e535c9" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>BentPlateGeometrySolver Class</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
             BentPlateGeometrySolver is a solver class to handle ConnectiveGeometry modification related computations.
             </div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Inheritance Hierarchy</span></div><div id="ID0RBSection" class="collapsibleSection"><span class="nolink">System<span id="LST17E7E832_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST17E7E832_0?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Object</span><br />  <span class="selflink">Tekla.Structures.Model<span id="LST17E7E832_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST17E7E832_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BentPlateGeometrySolver</span><br /></div><p> </p>
    <strong>Namespace:</strong> 
   <a href="ead2dd1b-97f2-a283-bd41-e985db80929d.htm">Tekla.Structures.Model</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Model (in Tekla.Structures.Model.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID1EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID1EBCA','cs','1','2');return false;">C#</a></div><div id="ID1EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID1EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID1EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID1EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID1EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">sealed</span> <span class="keyword">class</span> <span class="identifier">BentPlateGeometrySolver</span></pre></div><div id="ID1EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">NotInheritable</span> <span class="keyword">Class</span> <span class="identifier">BentPlateGeometrySolver</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID1EBCA");</script></div><p>The <span class="selflink">BentPlateGeometrySolver</span> type exposes the following members.</p><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Constructors</span></div><div id="ID3RBSection" class="collapsibleSection"><table class="members" id="constructorList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="fd8af369-d18d-821f-2a59-be7b6f97e022.htm">BentPlateGeometrySolver</a></td><td><div class="summary">
            Initializes a new instance of the BentPlateGeometrySolver class.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID4RB')" onkeypress="SectionExpandCollapse_CheckKey('ID4RB', event)" tabindex="0"><img id="ID4RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Methods</span></div><div id="ID4RBSection" class="collapsibleSection"><table class="members" id="methodList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="a2759dfe-8879-387a-43c8-a30e76609c81.htm">AddLeg(ConnectiveGeometry, Contour)</a></td><td><div class="summary">
            Appends a polygon section to ConnectiveGeometry, using the maximal radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="be684308-bd46-4b43-ab67-885df4db987f.htm">AddLeg(ConnectiveGeometry, Contour, Double)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="01139736-16e5-b503-b77c-2a989302924e.htm">AddLeg(ConnectiveGeometry, Contour, BentPlate<span id="LST17E7E832_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST17E7E832_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape)</a></td><td><div class="summary">
            Appends a polygon section to ConnectiveGeometry, using the maximal radius for the cylindrical connection, or
            the maximum cone aperture for conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="fe3ef7c1-95d0-b903-029f-3327db769d09.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified connection points and maximal radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="005a09fb-64f4-0150-fdee-40ba1d2e009e.htm">AddLeg(ConnectiveGeometry, Contour, Double, Double)</a></td><td><div class="summary">
            Joins a polygon section to this ConnectiveGeometry, using the specified radius and aperture for the conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="3381e0db-8efa-f82b-8322-f4a48ed1a265.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment, Double)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified connection points and radius for the cylindrical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="2ae3af3f-6bf8-1f24-e666-c55aca86f5c4.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment, BentPlate<span id="LST17E7E832_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST17E7E832_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape)</a></td><td><div class="summary">
            Appends a polygon section to this ConnectiveGeometry, using the specified connection points and maximal
            radius for the cylindrical connection, or maximum aperture for conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="253cf055-768d-0624-e258-2039cd78494d.htm">AddLeg(ConnectiveGeometry, LineSegment, Contour, LineSegment, Double, Double)</a></td><td><div class="summary">
            Joins a polygon section to this ConnectiveGeometry, using the specified connection points and radius
            and aperture for the conical connection.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="2d82eb90-c4a4-d473-b872-08e8522fa827.htm">ModifyBendSurface</a></td><td><div class="summary">
            Modifies the shape of a bend surface section, and updates related polygon sections accordingly.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="e2a50415-93e4-cc52-e702-0bab551f0a2d.htm">ModifyConicalRadiuses</a></td><td><div class="summary">
            Modify the radiuses of a conical section, preserving the length of the side boundaries. The order of the
            provided radiuses is not relevant, as the cone vertex will be located on the same side of the plates as
            the original cone section.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="9b20a6c3-4976-912f-a940-660056f80e3d.htm">ModifyCylindricalSurface</a></td><td><div class="summary">
            Modifies the shape of a cylindrical surface section, and updates related polygon sections accordingly.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="124f6069-da5d-82e5-0762-9266e5b30aed.htm">ModifyPolygon</a></td><td><div class="summary">
            Modify the shape of a polygon section, and updates related cylindrical sections accordingly.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="332d9017-9164-8a8b-5a1e-dc772f98674f.htm">ModifyRadius</a></td><td><div class="summary">
            Modify the radius of a cylindrical section.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="5426185f-4351-d659-7842-8a1e6256eb25.htm">RemoveLeg</a></td><td><div class="summary">
            Removes a polygon section which is the end section, from this ConnectiveGeometry including extensions and cylindrical surface.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ca3720e0-be3e-6960-ca2f-151a15227447.htm">ScaleConeSection</a></td><td><div class="summary">
            Scale the shape of a conical section.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="6480f6a8-c58d-c973-1e50-e90c49132b08.htm">SetBendAngle</a></td><td><div class="summary">
            Sets <span class="parameter">angle</span> as the angle of curved section <span class="parameter">sectionToSetAngle</span>
            and modifies <span class="parameter">geometry</span> starting from <span class="parameter">sectionToMove</span>.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="a9b78007-72d0-cdc5-7461-ffd5fc97c0d5.htm">SetMainSection</a></td><td><div class="summary">
            Sets <span class="parameter">newMainSection</span> as a main section of <span class="parameter">geometry</span>.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="5cac6160-6cf1-1bfb-b4da-d9c72fff026a.htm">Split</a></td><td><div class="summary">
            Returns the resulting geometry or geometries when a section and the related automatically created sections are removed from this geometry.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID5RB')" onkeypress="SectionExpandCollapse_CheckKey('ID5RB', event)" tabindex="0"><img id="ID5RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID5RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID1EAAABA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID1EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID1EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> Tekla.Structures.Geometry3d;
<span class="highlight-keyword">using</span> Tekla.Structures.Model;

<span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> Example
{
    <span class="highlight-keyword">var</span> contour1 = <span class="highlight-keyword">new</span> Contour();
    contour1.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">6000.0</span>, <span class="highlight-number">8500.0</span>, <span class="highlight-number">0.0</span>), <span class="highlight-keyword">null</span>));
    contour1.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">6000.0</span>, <span class="highlight-number">6000.0</span>, <span class="highlight-number">0.0</span>), <span class="highlight-keyword">null</span>));
    contour1.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">12000.0</span>, <span class="highlight-number">6000.0</span>, <span class="highlight-number">0.0</span>), <span class="highlight-keyword">null</span>));
    contour1.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">12000.0</span>, <span class="highlight-number">8500.0</span>, <span class="highlight-number">0.0</span>), <span class="highlight-keyword">null</span>));
    <span class="highlight-keyword">var</span> geometry = <span class="highlight-keyword">new</span> ConnectiveGeometry(contour1);

    <span class="highlight-keyword">var</span> contour2 = <span class="highlight-keyword">new</span> Contour();
    contour2.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">15000.0</span>, <span class="highlight-number">8500.0</span>, <span class="highlight-number">1000.0</span>), <span class="highlight-keyword">null</span>));
    contour2.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">15000.0</span>, <span class="highlight-number">6000.0</span>, <span class="highlight-number">1000.0</span>), <span class="highlight-keyword">null</span>));
    contour2.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">19600.0</span>, <span class="highlight-number">6000.0</span>, <span class="highlight-number">3500.0</span>), <span class="highlight-keyword">null</span>));
    contour2.AddContourPoint(<span class="highlight-keyword">new</span> ContourPoint(<span class="highlight-keyword">new</span> Point(<span class="highlight-number">19600.0</span>, <span class="highlight-number">8500.0</span>, <span class="highlight-number">3500.0</span>), <span class="highlight-keyword">null</span>));

    <span class="highlight-keyword">var</span> radius = <span class="highlight-number">2000.0</span>;
    <span class="highlight-keyword">var</span> bentPlateGeometrySolver = <span class="highlight-keyword">new</span> BentPlateGeometrySolver();
    <span class="highlight-keyword">var</span> newGeometry = bentPlateGeometrySolver.AddLeg(geometry, contour2, radius);
}</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID1EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID6RB')" onkeypress="SectionExpandCollapse_CheckKey('ID6RB', event)" tabindex="0"><img id="ID6RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID6RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="ead2dd1b-97f2-a283-bd41-e985db80929d.htm">Tekla.Structures.Model Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>