<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>CurvedDimensionSetHandler.CreateCurvedDimensionSetOrthogonal Method (ViewBase, Point, Point, Point, PointList, Double, CurvedDimensionSetOrthogonal.CurvedDimensionSetOrthogonalAttributes)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Tekla.Structures.Drawing.CurvedDimensionSetHandler.CreateCurvedDimensionSetOrthogonal(Tekla.Structures.Drawing.ViewBase,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Geometry3d.Point,Tekla.Structures.Drawing.PointList,System.Double,Tekla.Structures.Drawing.CurvedDimensionSetOrthogonal.CurvedDimensionSetOrthogonalAttributes)" /><meta name="Description" content="Creates a curved dimension set with orthogonal reference lines from the specified points and inserts it to the database." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Drawing" /><meta name="file" content="9ce6fb41-f2ea-6d9d-7a18-34a2644ba4ed" /><meta name="guid" content="9ce6fb41-f2ea-6d9d-7a18-34a2644ba4ed" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>CurvedDimensionSetHandler<span id="LSTB35B4618_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_0?cpp=::|nu=.");</script>CreateCurvedDimensionSetOrthogonal Method (ViewBase, Point, Point, Point, PointList, Double, CurvedDimensionSetOrthogonal<span id="LSTB35B4618_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_1?cpp=::|nu=.");</script>CurvedDimensionSetOrthogonalAttributes)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Creates a curved dimension set with orthogonal reference lines 
            from the specified points and inserts it to the database.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="77c95495-6298-e2ff-cdf9-2ad5ff176015.htm">Tekla.Structures.Drawing</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Drawing (in Tekla.Structures.Drawing.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">CurvedDimensionSetOrthogonal</span> <span class="identifier">CreateCurvedDimensionSetOrthogonal</span>(
	<span class="identifier">ViewBase</span> <span class="parameter">View</span>,
	<span class="identifier">Point</span> <span class="parameter">ArcPoint1</span>,
	<span class="identifier">Point</span> <span class="parameter">ArcPoint2</span>,
	<span class="identifier">Point</span> <span class="parameter">ArcPoint3</span>,
	<span class="identifier">PointList</span> <span class="parameter">DimensionPoints</span>,
	<span class="identifier">double</span> <span class="parameter">Distance</span>,
	<span class="identifier">CurvedDimensionSetOrthogonal<span id="LSTB35B4618_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetOrthogonalAttributes</span> <span class="parameter">Attributes</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">CreateCurvedDimensionSetOrthogonal</span> ( 
	<span class="parameter">View</span> <span class="keyword">As</span> <span class="identifier">ViewBase</span>,
	<span class="parameter">ArcPoint1</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">ArcPoint2</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">ArcPoint3</span> <span class="keyword">As</span> <span class="identifier">Point</span>,
	<span class="parameter">DimensionPoints</span> <span class="keyword">As</span> <span class="identifier">PointList</span>,
	<span class="parameter">Distance</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">Attributes</span> <span class="keyword">As</span> <span class="identifier">CurvedDimensionSetOrthogonal<span id="LSTB35B4618_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetOrthogonalAttributes</span>
) <span class="keyword">As</span> <span class="identifier">CurvedDimensionSetOrthogonal</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">View</span></dt><dd>Type: <a href="474d3089-26da-d62c-0797-bcae0f714220.htm">Tekla.Structures.Drawing<span id="LSTB35B4618_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>ViewBase</a><br />The view to be used.</dd><dt><span class="parameter">ArcPoint1</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LSTB35B4618_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_5?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The first arc point to be used.</dd><dt><span class="parameter">ArcPoint2</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LSTB35B4618_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_6?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The second arc point to be used.</dd><dt><span class="parameter">ArcPoint3</span></dt><dd>Type: <a href="c111c59a-fcae-cf59-bb15-632fb811ce4a.htm">Tekla.Structures.Geometry3d<span id="LSTB35B4618_7"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_7?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point</a><br />The third arc point to be used.</dd><dt><span class="parameter">DimensionPoints</span></dt><dd>Type: <a href="46ef3374-513f-103b-3d95-13a94c678f33.htm">Tekla.Structures.Drawing<span id="LSTB35B4618_8"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_8?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>PointList</a><br />The dimension points to be used.</dd><dt><span class="parameter">Distance</span></dt><dd>Type: <span class="nolink">System<span id="LSTB35B4618_9"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_9?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</span><br />The distance to be used.</dd><dt><span class="parameter">Attributes</span></dt><dd>Type: <a href="16c36036-7daa-fd1f-f952-c51698a43051.htm">Tekla.Structures.Drawing<span id="LSTB35B4618_10"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_10?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetOrthogonal<span id="LSTB35B4618_11"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB35B4618_11?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurvedDimensionSetOrthogonalAttributes</a><br />The attributes to be used.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="db6f6bf2-87e3-5f87-61f1-e8ecd39666d7.htm">CurvedDimensionSetOrthogonal</a><br />The created dimension set or null if failed.</div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="3b6dc735-5bad-9707-8004-f93b4f170e3b.htm">CurvedDimensionSetHandler Class</a></div><div class="seeAlsoStyle"><a href="f210c38c-549d-045e-b886-231dd83ab3e5.htm">CreateCurvedDimensionSetOrthogonal Overload</a></div><div class="seeAlsoStyle"><a href="77c95495-6298-e2ff-cdf9-2ad5ff176015.htm">Tekla.Structures.Drawing Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>