<html><head><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Operation.CreateBentPlateByFaces Method (Part, Face, Part, Face)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Tekla.Structures.Model.Operations.Operation.CreateBentPlateByFaces(Tekla.Structures.Model.Part,Tekla.Structures.Solid.Face,Tekla.Structures.Model.Part,Tekla.Structures.Solid.Face)" /><meta name="Description" content="Modifies the first plate by adding a cylindrical bend that connects it to the second plate creating a new instance based on two parts and selected faces in each part. See ." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Tekla.Structures.Model.Operations" /><meta name="file" content="f401c9ed-80c1-f692-6736-73d779c8577e" /><meta name="guid" content="f401c9ed-80c1-f692-6736-73d779c8577e" /><link rel="stylesheet" type="text/css" href="../styles/branding-Help1.css" /></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">Tekla Open API Reference for Tekla Structures 2025</div><div class="pageBody"><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="logoColumn"><img src="../icons/logo.png" /></td><td class="titleColumn"><h1>Operation<span id="LST6B984F06_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST6B984F06_0?cpp=::|nu=.");</script>CreateBentPlateByFaces Method (Part, Face, Part, Face)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Modifies the first plate by adding a cylindrical bend that connects it to the second plate
            creating a new <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a> instance based on two parts and selected faces in each part.
            See <a href="621e8e34-f192-2b5e-4be6-03ef655300ca.htm">CreateBentPlateByFaces(Part, Face, Part, Face, BentPlate<span id="LST6B984F06_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST6B984F06_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BendShape)</a>.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations</a><br />
    <strong>Assembly:</strong>
   Tekla.Structures.Model (in Tekla.Structures.Model.dll) Version: 2025.0.0-alpha00048669+a99462f17964bc42624ada6e8d316db2d795d226<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">BentPlate</span> <span class="identifier">CreateBentPlateByFaces</span>(
	<span class="identifier">Part</span> <span class="parameter">part1</span>,
	<span class="identifier">Face</span> <span class="parameter">face1</span>,
	<span class="identifier">Part</span> <span class="parameter">part2</span>,
	<span class="identifier">Face</span> <span class="parameter">face2</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CreateBentPlateByFaces</span> ( 
	<span class="parameter">part1</span> <span class="keyword">As</span> <span class="identifier">Part</span>,
	<span class="parameter">face1</span> <span class="keyword">As</span> <span class="identifier">Face</span>,
	<span class="parameter">part2</span> <span class="keyword">As</span> <span class="identifier">Part</span>,
	<span class="parameter">face2</span> <span class="keyword">As</span> <span class="identifier">Face</span>
) <span class="keyword">As</span> <span class="identifier">BentPlate</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">part1</span></dt><dd>Type: <a href="ac720ea3-a9ae-235b-d627-c9c37585b6ec.htm">Tekla.Structures.Model<span id="LST6B984F06_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST6B984F06_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Part</a><br />The first part.</dd><dt><span class="parameter">face1</span></dt><dd>Type: <a href="5831d571-d8ee-b975-19be-799d8dcb1439.htm">Tekla.Structures.Solid<span id="LST6B984F06_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST6B984F06_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Face</a><br />The selected face on the first part.</dd><dt><span class="parameter">part2</span></dt><dd>Type: <a href="ac720ea3-a9ae-235b-d627-c9c37585b6ec.htm">Tekla.Structures.Model<span id="LST6B984F06_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST6B984F06_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Part</a><br />The second part.</dd><dt><span class="parameter">face2</span></dt><dd>Type: <a href="5831d571-d8ee-b975-19be-799d8dcb1439.htm">Tekla.Structures.Solid<span id="LST6B984F06_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST6B984F06_5?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Face</a><br />The selected face on the second part.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="a75e430c-a12d-1753-65b0-f93472716a4a.htm">BentPlate</a><br />The bent plate object if successful, null otherwise.</div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="d5bbc096-a164-49ea-16a8-3820e40b00be.htm">Operation Class</a></div><div class="seeAlsoStyle"><a href="fe47d253-6b7e-3119-0f20-5ba244c9fd65.htm">CreateBentPlateByFaces Overload</a></div><div class="seeAlsoStyle"><a href="e1b7c3a4-9e84-2646-0fba-d6b4dd8481c5.htm">Tekla.Structures.Model.Operations Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p>Copyright © 1992-2025 Trimble Solutions Corporation and its licensors. All rights reserved.</p> </div></body></html>